using System;
using System.Collections.Generic;
using System.Text;

namespace MSTnTAPP.Util
{
    public static class OfflineAPIResponse
    {
        public static string GetRecentSearch = "{\"ReturnCode\":\"ERR_SUCCESS\",\"ReturnMessage\":\"\",\"Shipments\":[{\"ConsigneeName\":\"ABC Inc.\",\"CustomerReference\":\"CUST111\",\"DateSailed\":\"\\/Date(1571136365897+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Southampton\",\"JobId\":\"JB0001\",\"JobReferenceNumber\":\"J0001\",\"JobType\":\"JTYP100\",\"Pieces\":\"5\",\"PlaceOfReceipt\":\"Leeds\",\"PortOfDischarge\":\"PortDisch1\",\"PortOfLoading\":\"PortLoad1\",\"ShipperName\":\"Test Shipper 1\",\"Summary\":\"On Schedule\",\"TransportDirection\":\"Export\",\"TransportType\":\"Sea\",\"VesselName\":\"VES-1001\"},{\"ConsigneeName\":\"Carter Inc.\",\"CustomerReference\":\"CUST112\",\"DateSailed\":\"\\/Date(1571136365899+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Southampton\",\"JobId\":\"JB0002\",\"JobReferenceNumber\":\"J0002\",\"JobType\":\"JTYP100\",\"Pieces\":\"10\",\"PlaceOfReceipt\":\"Oxford\",\"PortOfDischarge\":\"PortDisch2\",\"PortOfLoading\":\"PortLoad2\",\"ShipperName\":\"Test Shipper 2\",\"Summary\":\"On Schedule\",\"TransportDirection\":\"Import\",\"TransportType\":\"Sea\",\"VesselName\":\"VES-1002\"},{\"ConsigneeName\":\"Fedex Inc.\",\"CustomerReference\":\"CUST113\",\"DateSailed\":\"\\/Date(1571136365899+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Cambridge\",\"JobId\":\"JB0003\",\"JobReferenceNumber\":\"J0003\",\"JobType\":\"JTYP101\",\"Pieces\":\"3\",\"PlaceOfReceipt\":\"Oxford\",\"PortOfDischarge\":\"PortDisch4\",\"PortOfLoading\":\"PortLoad4\",\"ShipperName\":\"Test Shipper 4\",\"Summary\":\"On Schedule\",\"TransportDirection\":\"Export\",\"TransportType\":\"Air\",\"VesselName\":\"VES-1004\"},{\"ConsigneeName\":\"Fedex Inc.\",\"CustomerReference\":\"CUST115\",\"DateSailed\":\"\\/Date(1571136365899+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Cambridge\",\"JobId\":\"JB0005\",\"JobReferenceNumber\":\"J0004\",\"JobType\":\"JTYP105\",\"Pieces\":\"8\",\"PlaceOfReceipt\":\"Oxford\",\"PortOfDischarge\":\"PortDisch5\",\"PortOfLoading\":\"PortLoad5\",\"ShipperName\":\"Test Shipper 5\",\"Summary\":\"On Schedule\",\"TransportDirection\":\"Import\",\"TransportType\":\"Air\",\"VesselName\":\"VES-1005\"},{\"ConsigneeName\":\"Fedex Inc.\",\"CustomerReference\":\"CUST116\",\"DateSailed\":\"\\/Date(1571136365899+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Cambridge\",\"JobId\":\"JB0006\",\"JobReferenceNumber\":\"J0006\",\"JobType\":\"JTYP106\",\"Pieces\":\"3\",\"PlaceOfReceipt\":\"Oxford\",\"PortOfDischarge\":\"PortDisch6\",\"PortOfLoading\":\"PortLoad6\",\"ShipperName\":\"Test Shipper 6\",\"Summary\":\"Delayed\",\"TransportDirection\":\"Export\",\"TransportType\":\"Land\",\"VesselName\":\"VES-1006\"}]}";
        public static string GetShipments = "{\"ReturnCode\":\"ERR_SUCCESS\",\"ReturnMessage\":\"\",\"Shipments\":[{\"ConsigneeName\":\"ABC Inc.\",\"CustomerReference\":\"CUST111\",\"DateSailed\":\"\\/Date(1571136365897+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Southampton\",\"JobId\":\"JB0001\",\"JobReferenceNumber\":\"J0001\",\"JobType\":\"JTYP100\",\"Pieces\":\"5\",\"PlaceOfReceipt\":\"Leeds\",\"PortOfDischarge\":\"PortDisch1\",\"PortOfLoading\":\"PortLoad1\",\"ShipperName\":\"Test Shipper 1\",\"Summary\":\"On Schedule\",\"TransportDirection\":\"Export\",\"TransportType\":\"Sea\",\"VesselName\":\"VES-1001\"},{\"ConsigneeName\":\"Carter Inc.\",\"CustomerReference\":\"CUST112\",\"DateSailed\":\"\\/Date(1571136365899+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Southampton\",\"JobId\":\"JB0002\",\"JobReferenceNumber\":\"J0002\",\"JobType\":\"JTYP100\",\"Pieces\":\"10\",\"PlaceOfReceipt\":\"Oxford\",\"PortOfDischarge\":\"PortDisch2\",\"PortOfLoading\":\"PortLoad2\",\"ShipperName\":\"Test Shipper 2\",\"Summary\":\"On Schedule\",\"TransportDirection\":\"Import\",\"TransportType\":\"Sea\",\"VesselName\":\"VES-1002\"},{\"ConsigneeName\":\"Fedex Inc.\",\"CustomerReference\":\"CUST113\",\"DateSailed\":\"\\/Date(1571136365899+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Cambridge\",\"JobId\":\"JB0003\",\"JobReferenceNumber\":\"J0003\",\"JobType\":\"JTYP101\",\"Pieces\":\"3\",\"PlaceOfReceipt\":\"Oxford\",\"PortOfDischarge\":\"PortDisch4\",\"PortOfLoading\":\"PortLoad4\",\"ShipperName\":\"Test Shipper 4\",\"Summary\":\"On Schedule\",\"TransportDirection\":\"Export\",\"TransportType\":\"Air\",\"VesselName\":\"VES-1004\"},{\"ConsigneeName\":\"Fedex Inc.\",\"CustomerReference\":\"CUST115\",\"DateSailed\":\"\\/Date(1571136365899+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Cambridge\",\"JobId\":\"JB0005\",\"JobReferenceNumber\":\"J0004\",\"JobType\":\"JTYP105\",\"Pieces\":\"8\",\"PlaceOfReceipt\":\"Oxford\",\"PortOfDischarge\":\"PortDisch5\",\"PortOfLoading\":\"PortLoad5\",\"ShipperName\":\"Test Shipper 5\",\"Summary\":\"On Schedule\",\"TransportDirection\":\"Import\",\"TransportType\":\"Air\",\"VesselName\":\"VES-1005\"},{\"ConsigneeName\":\"Fedex Inc.\",\"CustomerReference\":\"CUST116\",\"DateSailed\":\"\\/Date(1571136365899+0530)\\/\",\"ETA\":\"\\/Date(1571136365899+0530)\\/\",\"FinalDestination\":\"Cambridge\",\"JobId\":\"JB0006\",\"JobReferenceNumber\":\"J0006\",\"JobType\":\"JTYP106\",\"Pieces\":\"3\",\"PlaceOfReceipt\":\"Oxford\",\"PortOfDischarge\":\"PortDisch6\",\"PortOfLoading\":\"PortLoad6\",\"ShipperName\":\"Test Shipper 6\",\"Summary\":\"Delayed\",\"TransportDirection\":\"Export\",\"TransportType\":\"Land\",\"VesselName\":\"VES-1006\"}]}";
        public static string GetTrackingdata = "{\"ReturnCode\":\"ERR_SUCCESS\",\"ReturnMessage\":\"\",\"TrackingInfoList\":[{\"ConfirmedActual\":\"\\/Date(1573541896897+0530)\\/\",\"CurrentEstimated\":\"\\/Date(1573541896899+0530)\\/\",\"LocationName\":\"NHAVA SHEVA\",\"LocationType\":\"Order Received\\/Created\",\"OriginalEstimated\":\"\\/Date(1573541896899+0530)\\/\"},{\"ConfirmedActual\":null,\"CurrentEstimated\":null,\"LocationName\":\"NHAVA SHEVA\",\"LocationType\":\"Place of Receipt\",\"OriginalEstimated\":null},{\"ConfirmedActual\":\"\\/Date(1573541896899+0530)\\/\",\"CurrentEstimated\":\"\\/Date(1573541896899+0530)\\/\",\"LocationName\":\"NHAVA SHEVA\",\"LocationType\":\"Port of Loading\",\"OriginalEstimated\":\"\\/Date(1573541896899+0530)\\/\"},{\"ConfirmedActual\":\"\\/Date(1573541896899+0530)\\/\",\"CurrentEstimated\":\"\\/Date(1573541896899+0530)\\/\",\"LocationName\":\"SOUTHAMPTON\",\"LocationType\":\"Port of Discharge\",\"OriginalEstimated\":\"\\/Date(1573541896899+0530)\\/\"},{\"ConfirmedActual\":null,\"CurrentEstimated\":null,\"LocationName\":\"HARLOW\",\"LocationType\":\"Final Destination\",\"OriginalEstimated\":null}]}";
        public static string GetAddressParties = "{\"ReturnCode\":\"ERR_SUCCESS\",\"ReturnMessage\":\"\",\"AddressParties\":[{\"AddressName\":\"BHARANYA EXPORTS ECO VISION\",\"AddressType\":\"Shipper\"},{\"AddressName\":\"BUNZL CATERING SUPPLIES\",\"AddressType\":\"Consignee\"},{\"AddressName\":\"CMA CGM GROUP\",\"AddressType\":\"Carrier\"}]}";
        public static string GetReferences = "{\"ReturnCode\":\"ERR_SUCCESS\",\"ReturnMessage\":\"\",\"References\":[{\"Name\":\"Shipper Reference\",\"Value\":\"883527\"},{\"Name\":\"Importers Reference\",\"Value\":\"883527\"},{\"Name\":\"Vessel\",\"Value\":\"CPO BREMEN\"},{\"Name\":\"Ocean Bill Number\",\"Value\":\"18019128414\"},{\"Name\":\"Voyage Reference\",\"Value\":\"0EG3ZW1MA\"},{\"Name\":\"Import Customs Reference\",\"Value\":\"9GB346231375000-J425865\"},{\"Name\":\"Pieces\",\"Value\":\"1246\"},{\"Name\":\"Cube\",\"Value\":\"25\"},{\"Name\":\"Weight\",\"Value\":\"6239\"},{\"Name\":\"Chargeable Weight\",\"Value\":\"25\"}]}";
    }
}
